version: "3.9"

services:
  animeai:
    build: .
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
