CREATE TABLE IF NOT EXISTS anime (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    categoria VARCHAR(50),
    ano_lancamento DATE,
    num_episodios INT
);